# Generated by Django 3.1.4 on 2021-09-11 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentdata', '0002_remove_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studentdata.address'),
            preserve_default=False,
        ),
    ]
